flowchart LR
    n_DevelopmentTools["DevelopmentTools (unit)"]
    n_G5M4RetirePython["G5M4RetirePython (activity)"]
    n_RetireReplacedPythonEntryPoints["RetireReplacedPythonEntryPoints (functionality)"]
    n_DevelopmentTools -->|owns| n_RetireReplacedPythonEntryPoints
    n_G5M4RetirePython -->|addresses| n_RetireReplacedPythonEntryPoints
