sequenceDiagram
    participant n_FyneBackend as Fyne Backend
    participant n_SduiDispatcher as Sdui Dispatcher
    n_FyneBackend->>n_SduiDispatcher: 1: Ui Action Request (Native Ui Actions)
    n_SduiDispatcher-->>n_FyneBackend: 2: Ui Action Rejected (Native Ui Actions) reply-to 1
