sequenceDiagram
    participant n_ReloadCoordinator as ReloadCoordinator
    participant n_SduiFrontend as SduiFrontend
    participant n_SourceWatcher as SourceWatcher
    n_SourceWatcher->>n_ReloadCoordinator: 1: ReloadRequest (ModelReloadCalls)
    n_ReloadCoordinator->>n_SduiFrontend: 2: CompileUiRequest (UiCompilationCalls)
    n_SduiFrontend-->>n_ReloadCoordinator: 3: CompileUiRejected (UiCompilationCalls) reply-to 2
    n_ReloadCoordinator-->>n_SourceWatcher: 4: ReloadRejected (ModelReloadCalls) reply-to 1
