sequenceDiagram
    participant n_XfmdDocumentHost as Xfmd Document Host
    participant n_DocumentBroker as Document Broker
    participant n_SdlViewpointGenerator as Sdl Viewpoint Generator
    n_XfmdDocumentHost->>n_DocumentBroker: 1: Select View Request (View Navigation Calls)
    n_DocumentBroker->>n_SdlViewpointGenerator: 2: Project View Request (View Projection Calls)
    n_SdlViewpointGenerator-->>n_DocumentBroker: 3: View Projection Rejected (View Projection Calls) reply-to 2
    n_DocumentBroker-->>n_XfmdDocumentHost: 4: View Request Rejected (View Navigation Calls) reply-to 1
