flowchart LR
    n_UiGenerationEventsProtocol["UiGenerationEventsProtocol (contract)"]
    n_UiGenerationNotices["UiGenerationNotices (datagram)"]
    n_UiGenerationEventsProtocol -->|permits| n_UiGenerationNotices
