// Package codegen emits constructors for the executable action-core profile.
package codegen

import (
	"fmt"
	ui "github.com/Hans-Einar/SDP/SDUI/go/codegen"
	"github.com/Hans-Einar/SDP/SystemDesignLanguage/go/documents"
	"github.com/Hans-Einar/SDP/SystemDesignLanguage/go/parser"
	"go/format"
)

const Version = "sdl-go-model/1"
const ParserPackage = "github.com/Hans-Einar/SDP/SystemDesignLanguage/go/parser"

func Generate(source, pkg string) ([]byte, error) {
	if !ui.ValidPackage(pkg) {
		return nil, fmt.Errorf("invalid package name")
	}
	p, e := parser.CompileActions(source)
	if e != nil {
		return nil, e
	}
	literal, e := ui.Literal(p, map[string]string{ParserPackage: "sdl"})
	if e != nil {
		return nil, e
	}
	return format.Source([]byte(fmt.Sprintf("// Code generated by %s; DO NOT EDIT.\npackage %s\nimport sdl %q\nconst SDLSourceSHA256 = %q\nfunc Program() *sdl.Program { return %s }\n", Version, pkg, ParserPackage, documents.Hash([]byte(source)), literal)))
}
func Bundle(actions, source, entry, pkg string) (*documents.Bundle, error) {
	a, e := Generate(actions, pkg)
	if e != nil {
		return nil, e
	}
	s, e := ui.Generate(source, entry, pkg)
	if e != nil {
		return nil, e
	}
	b := &documents.Bundle{Files: map[string][]byte{"actions_gen.go": a, "ui_gen.go": s}, Manifest: documents.Manifest{Version: Version + "/" + ui.Version, Revision: documents.Hash([]byte(actions + "\x00" + source))}}
	b.Seal()
	return b, nil
}
