// Code generated by sdui-go-model/1; DO NOT EDIT.
package generatedmodel

import ui "github.com/Hans-Einar/SDP/SDUI/go/parser"

const UISourceSHA256 = "4a39f150b4a9745d83d116154812d3b6066385f6038abbc73dc40858878f9af6"

func Document() *ui.Document {
	return func() *ui.Document {
		v := ui.Document{Profile: string("sdui/0.2"), References: []ui.ModuleRef{ui.ModuleRef{Alias: string("apt"), Path: string("edit-apt-cell.sdl"), Span: ui.Span{Start: int(10), End: int(39), Line: int(2), Column: int(1)}}}, Definitions: []ui.Definition{ui.Definition{Name: string("page"), Root: func() *ui.Node {
			v := ui.Node{Kind: string("frame"), Name: nil, Role: nil, Rows: []ui.Row{ui.Row{Items: []*ui.Node{func() *ui.Node {
				v := ui.Node{Kind: string("markdown"), Name: nil, Role: func() *string { v := string("header"); return &v }(), Rows: nil, Widget: nil, Arguments: nil, Text: func() *ui.Literal {
					v := ui.Literal{Kind: string("string"), Value: string("## EditAptCell · simulert domene"), Span: ui.Span{Start: int(58), End: int(93), Line: int(4), Column: int(10)}}
					return &v
				}(), Target: nil, Variant: nil, Layout: nil, Span: ui.Span{Start: int(51), End: int(93), Line: int(4), Column: int(3)}}
				return &v
			}(), func() *ui.Node {
				v := ui.Node{Kind: string("markdown"), Name: nil, Role: nil, Rows: nil, Widget: nil, Arguments: nil, Text: func() *ui.Literal {
					v := ui.Literal{Kind: string("string"), Value: string("Celle LengthA1 · eksempelverdi 400. Prøven godtar heltall 100–1000.\nDette er ikke Ponsse-domenevalidering eller maskinkontroll."), Span: ui.Span{Start: int(97), End: int(231), Line: int(5), Column: int(3)}}
					return &v
				}(), Target: nil, Variant: nil, Layout: nil, Span: ui.Span{Start: int(97), End: int(231), Line: int(5), Column: int(3)}}
				return &v
			}()}, Span: ui.Span{Start: int(51), End: int(231), Line: int(4), Column: int(3)}}, ui.Row{Items: []*ui.Node{func() *ui.Node {
				v := ui.Node{Kind: string("widget"), Name: func() *string { v := string("value"); return &v }(), Role: nil, Rows: nil, Widget: func() *string { v := string("input"); return &v }(), Arguments: []ui.Argument{ui.Argument{Name: nil, Value: ui.Literal{Kind: string("string"), Value: string("Lengdeverdi"), Span: ui.Span{Start: int(247), End: int(260), Line: int(6), Column: int(15)}}, Span: ui.Span{Start: int(247), End: int(260), Line: int(6), Column: int(15)}}, ui.Argument{Name: func() *string { v := string("value"); return &v }(), Value: ui.Literal{Kind: string("string"), Value: string("400"), Span: ui.Span{Start: int(268), End: int(273), Line: int(6), Column: int(36)}}, Span: ui.Span{Start: int(262), End: int(273), Line: int(6), Column: int(30)}}, ui.Argument{Name: func() *string { v := string("callback"); return &v }(), Value: ui.Reference{Module: string("apt"), Object: string("EditAptCell"), Member: string("invoke"), Span: ui.Span{Start: int(284), End: int(307), Line: int(6), Column: int(52)}}, Span: ui.Span{Start: int(275), End: int(307), Line: int(6), Column: int(43)}}}, Text: nil, Target: nil, Variant: nil, Layout: nil, Span: ui.Span{Start: int(235), End: int(308), Line: int(6), Column: int(3)}}
				return &v
			}(), func() *ui.Node {
				v := ui.Node{Kind: string("widget"), Name: func() *string { v := string("apply"); return &v }(), Role: nil, Rows: nil, Widget: func() *string { v := string("button"); return &v }(), Arguments: []ui.Argument{ui.Argument{Name: nil, Value: ui.Literal{Kind: string("string"), Value: string("Godta celle"), Span: ui.Span{Start: int(325), End: int(338), Line: int(7), Column: int(16)}}, Span: ui.Span{Start: int(325), End: int(338), Line: int(7), Column: int(16)}}, ui.Argument{Name: func() *string { v := string("callback"); return &v }(), Value: ui.Reference{Module: string("apt"), Object: string("EditAptCell"), Member: string("invoke"), Span: ui.Span{Start: int(349), End: int(372), Line: int(7), Column: int(40)}}, Span: ui.Span{Start: int(340), End: int(372), Line: int(7), Column: int(31)}}}, Text: nil, Target: nil, Variant: nil, Layout: nil, Span: ui.Span{Start: int(312), End: int(373), Line: int(7), Column: int(3)}}
				return &v
			}()}, Span: ui.Span{Start: int(235), End: int(373), Line: int(6), Column: int(3)}}, ui.Row{Items: []*ui.Node{func() *ui.Node {
				v := ui.Node{Kind: string("markdown"), Name: nil, Role: nil, Rows: nil, Widget: nil, Arguments: nil, Text: func() *ui.Literal {
					v := ui.Literal{Kind: string("string"), Value: string("Enter eller knappen sender draft og forventet domenerevisjon. Escape forkaster lokal redigering."), Span: ui.Span{Start: int(377), End: int(475), Line: int(8), Column: int(3)}}
					return &v
				}(), Target: nil, Variant: nil, Layout: nil, Span: ui.Span{Start: int(377), End: int(475), Line: int(8), Column: int(3)}}
				return &v
			}()}, Span: ui.Span{Start: int(377), End: int(475), Line: int(8), Column: int(3)}}}, Widget: nil, Arguments: nil, Text: nil, Target: nil, Variant: func() *string { v := string("b"); return &v }(), Layout: []ui.LayoutRule{ui.LayoutRule{Name: string("scale"), Value: ui.Literal{Kind: string("number"), Value: float64(1), Span: ui.Span{Start: int(487), End: int(488), Line: int(9), Column: int(12)}}, Spelling: string("scale=1"), Span: ui.Span{Start: int(481), End: int(488), Line: int(9), Column: int(6)}}, ui.LayoutRule{Name: string("padding"), Value: ui.Literal{Kind: string("number"), Value: float64(0.02), Span: ui.Span{Start: int(497), End: int(501), Line: int(9), Column: int(22)}}, Spelling: string("padding=0.02"), Span: ui.Span{Start: int(489), End: int(501), Line: int(9), Column: int(14)}}}, Span: ui.Span{Start: int(47), End: int(502), Line: int(3), Column: int(8)}}
			return &v
		}(), Span: ui.Span{Start: int(40), End: int(503), Line: int(3), Column: int(1)}}}, Connections: []ui.Connection{ui.Connection{Module: string("apt"), Object: string("EditAptCell"), Definition: string("page"), Path: []string{string("value")}, Span: ui.Span{Start: int(504), End: int(542), Line: int(10), Column: int(1)}}}, Span: ui.Span{Start: int(0), End: int(543), Line: int(1), Column: int(1)}}
		return &v
	}()
}
func Root() *ui.Instance {
	return func() *ui.Instance {
		v := ui.Instance{Kind: string("frame"), Path: string("page"), Variant: string("box"), Widget: string(""), Text: string(""), Arguments: map[string]any{}, Layout: map[string]any{"padding": float64(0.02), "scale": float64(1)}, Rows: [][]*ui.Instance{[]*ui.Instance{func() *ui.Instance {
			v := ui.Instance{Kind: string("markdown"), Path: string("page/$r0c1"), Variant: string(""), Widget: string(""), Text: string("Celle LengthA1 · eksempelverdi 400. Prøven godtar heltall 100–1000.\nDette er ikke Ponsse-domenevalidering eller maskinkontroll."), Arguments: map[string]any{}, Layout: map[string]any{}, Rows: [][]*ui.Instance{}, Regions: []ui.Region{}, Span: ui.Span{Start: int(97), End: int(231), Line: int(5), Column: int(3)}}
			return &v
		}()}, []*ui.Instance{func() *ui.Instance {
			v := ui.Instance{Kind: string("widget"), Path: string("page/value"), Variant: string(""), Widget: string("input"), Text: string(""), Arguments: map[string]any{"callback": ui.Reference{Module: string("apt"), Object: string("EditAptCell"), Member: string("invoke"), Span: ui.Span{Start: int(284), End: int(307), Line: int(6), Column: int(52)}}, "text": ui.Literal{Kind: string("string"), Value: string("Lengdeverdi"), Span: ui.Span{Start: int(247), End: int(260), Line: int(6), Column: int(15)}}, "value": ui.Literal{Kind: string("string"), Value: string("400"), Span: ui.Span{Start: int(268), End: int(273), Line: int(6), Column: int(36)}}}, Layout: map[string]any{}, Rows: [][]*ui.Instance{}, Regions: []ui.Region{}, Span: ui.Span{Start: int(235), End: int(308), Line: int(6), Column: int(3)}}
			return &v
		}(), func() *ui.Instance {
			v := ui.Instance{Kind: string("widget"), Path: string("page/apply"), Variant: string(""), Widget: string("button"), Text: string(""), Arguments: map[string]any{"callback": ui.Reference{Module: string("apt"), Object: string("EditAptCell"), Member: string("invoke"), Span: ui.Span{Start: int(349), End: int(372), Line: int(7), Column: int(40)}}, "label": ui.Literal{Kind: string("string"), Value: string("Godta celle"), Span: ui.Span{Start: int(325), End: int(338), Line: int(7), Column: int(16)}}}, Layout: map[string]any{}, Rows: [][]*ui.Instance{}, Regions: []ui.Region{}, Span: ui.Span{Start: int(312), End: int(373), Line: int(7), Column: int(3)}}
			return &v
		}()}, []*ui.Instance{func() *ui.Instance {
			v := ui.Instance{Kind: string("markdown"), Path: string("page/$r2c0"), Variant: string(""), Widget: string(""), Text: string("Enter eller knappen sender draft og forventet domenerevisjon. Escape forkaster lokal redigering."), Arguments: map[string]any{}, Layout: map[string]any{}, Rows: [][]*ui.Instance{}, Regions: []ui.Region{}, Span: ui.Span{Start: int(377), End: int(475), Line: int(8), Column: int(3)}}
			return &v
		}()}}, Regions: []ui.Region{ui.Region{Role: string("header"), Node: func() *ui.Instance {
			v := ui.Instance{Kind: string("markdown"), Path: string("page/header"), Variant: string(""), Widget: string(""), Text: string("## EditAptCell · simulert domene"), Arguments: map[string]any{}, Layout: map[string]any{}, Rows: [][]*ui.Instance{}, Regions: []ui.Region{}, Span: ui.Span{Start: int(51), End: int(93), Line: int(4), Column: int(3)}}
			return &v
		}()}}, Span: ui.Span{Start: int(47), End: int(502), Line: int(3), Column: int(8)}}
		return &v
	}()
}
