#!/usr/bin/env bash
# Reproduce E3 model evidence through existing Go tools; no source assembler.
set -euo pipefail
repo_root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../../.." && pwd)
go_tool=${SDP_GO:-go}
command -v "$go_tool" >/dev/null || { echo 'Set SDP_GO to an installed Go executable.' >&2; exit 2; }
command -v jq >/dev/null || { echo 'jq is required.' >&2; exit 2; }
output=${1:-$(mktemp -d "${TMPDIR:-/tmp}/sdp-ecosystems.XXXXXX")}
mkdir -p -- "$output"
output=$(cd -- "$output" && pwd)
case "$output/" in "$repo_root/"*) echo 'Choose an output directory outside the repository.' >&2; exit 2;; esac
if [[ -n $(ls -A -- "$output") ]]; then
  echo 'Choose an empty output directory; existing evidence is never overwritten.' >&2; exit 2
fi
mkdir "$output/bin"
(cd "$repo_root/SDL/go" && "$go_tool" build -o "$output/bin/sdl" ./cmd/sdl)
(cd "$repo_root/SDPTool" && "$go_tool" build -o "$output/bin/sdptool" ./cmd/sdptool)
"$go_tool" version > "$output/toolchain.txt"
git -C "$repo_root" rev-parse HEAD > "$output/source-commit.txt"
sha256sum "$output/bin/sdl" "$output/bin/sdptool" > "$output/tool-hashes.txt"
"$output/bin/sdptool" "$repo_root" discover > "$output/discovery.json"
jq -e '.status == "valid" or .status == "recognized"' "$output/discovery.json" >/dev/null
registration="$repo_root/SDP/navigation.json"
jq -e '[.models[].id] | length == (unique | length)' "$registration" >/dev/null
jq -e '[.models[] | select(.source | startswith("SDP/SDL/"))] | length > 0' "$registration" >/dev/null
printf '# SDP ecosystem model previews\n\nGenerated by existing SDL tools. These are architecture models, not runtime evidence.\n\n' > "$output/index.md"
: > "$output/results.ndjson"
while IFS=$'\t' read -r model_id model_source; do
  model_dir="$output/$model_id"
  mkdir "$model_dir"
  "$output/bin/sdl" check "$repo_root/$model_source" > "$model_dir/check.json"
  jq -e '.valid == true' "$model_dir/check.json" >/dev/null
  "$output/bin/sdl" ast "$repo_root/$model_source" > "$model_dir/ast.json"
  "$output/bin/sdl" format "$repo_root/$model_source" > "$model_dir/canonical.design"
  "$output/bin/sdl" check "$model_dir/canonical.design" > "$model_dir/canonical-check.json"
  "$output/bin/sdptool" "$repo_root" tree --model "$model_id" > "$model_dir/tree.json"
  selection_uri=$(jq -er '[.nodes[] | select(.kind == "diagram" and .target.operation == "select")][0].target.uri' "$model_dir/tree.json")
  selection_revision=$(jq -er '.revision' "$model_dir/tree.json")
  "$output/bin/sdptool" "$repo_root" select --model "$model_id" --uri "$selection_uri" --revision "$selection_revision" --output "$model_dir/selected" > "$model_dir/selected.json"
  test -s "$model_dir/selected/entry.md"
  "$output/bin/sdl" viewpoints "$repo_root/$model_source" --output "$model_dir/views" --format static --viewpoint "${SDP_VIEWPOINTS:-VP01,VP02,VP06,VP08}" > "$model_dir/export.json"
  source_hash=$(sha256sum "$repo_root/$model_source" | cut -d ' ' -f 1)
  jq -n --arg id "$model_id" --arg source "$model_source" --arg sha256 "$source_hash" --slurpfile result "$model_dir/export.json" '{id:$id,source:$source,sha256:$sha256,valid:true,export:$result[0]}' >> "$output/results.ndjson"
  printf -- '- [%s](%s/views/index.md) — [source](%s)\n' "$model_id" "$model_id" "$repo_root/$model_source" >> "$output/index.md"
  printf 'PASS %s\n' "$model_id"
done < <(jq -r '.models[] | select(.source | startswith("SDP/SDL/")) | [.id,.source] | @tsv' "$registration")
jq -s '{schema:"sdp-ecosystem-verification/1",models:.,claim:"Structural parsing, AST, canonical reparse, registered navigation, revision-bound selection and static generation only"}' "$output/results.ndjson" > "$output/results.json"
printf 'Evidence and generated Markdown: %s\n' "$output"
