#!/usr/bin/env python3
"""Reproduce a bounded SDL-generated IPD review; no installation or renderer edits."""
import argparse
from collections import Counter
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import tempfile
from urllib.parse import urlencode

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]
MODEL = Path('SDP/03--Architecture/SDPTool.design')
BASELINE = 'db7d82d'
SELECTIONS = [
    ('01-use-cases', 'Installation use cases', 'VP01', {'focus': 'ProjectMaintainer', 'relations': 'pursues,supports', 'depth': '2'}),
    ('02-engine', 'SDPTool ownership', 'VP02', {'diagram': 'VP02-SdpToolProcess'}),
    ('03-client', 'Thin client boundary', 'VP02', {'diagram': 'VP02-GhSdpProcess'}),
    ('04-plan-allocation', 'Planning feature allocation', 'VP07', {'diagram': 'VP07-SdpTool-InstallationPlanning'}),
    ('05-apply-allocation', 'Apply feature allocation', 'VP07', {'diagram': 'VP07-SdpTool-InstallationExecution'}),
    ('06-delivery', 'Delivery dependencies', 'VP06', {'diagram': 'VP06-dependencies'}),
    ('07-bootstrap', 'Executable bootstrap', 'VP08', {'diagram': 'VP08-SdpToolBootstrapPrepared'}),
    ('08-plan', 'Plan preparation', 'VP08', {'diagram': 'VP08-InstallationPlanPrepared'}),
    ('09-apply', 'Apply and finalization', 'VP08', {'diagram': 'VP08-InstallationApplied'}),
    ('10-resume', 'Resume and finalization', 'VP08', {'diagram': 'VP08-InstallationResumed'}),
    ('11-reject', 'Pre-mutation drift rejection', 'VP08', {'diagram': 'VP08-InstallationDriftRejected'}),
    ('12-receipt', 'Installed receipt storage', 'VP09', {'diagram': 'VP09-data-InstalledProcessRecords'}),
    ('13-journal', 'Operation journal storage', 'VP09', {'diagram': 'VP09-data-InstallationOperationRecords'}),
    ('14-release', 'Release inventory storage', 'VP09', {'diagram': 'VP09-data-ProcessReleaseRecords'}),
    ('15-plan-record', 'Reviewed plan data', 'VP09', {'diagram': 'VP09-data-ReviewedInstallationPlans'}),
]


def digest(data):
    return hashlib.sha256(data).hexdigest()


def run(tool, *args):
    return subprocess.run([str(tool), *map(str, args)], cwd=ROOT, check=True,
                          capture_output=True, text=True).stdout


def checks(tool):
    source = (ROOT / MODEL).read_text()
    report = json.loads(run(tool, 'ast', MODEL))
    assert report['valid'] and not report['diagnostics']
    before = subprocess.check_output(['git', 'show', BASELINE + ':' + str(MODEL)], cwd=ROOT, text=True)
    assert set(before.splitlines()) <= set(source.splitlines()), 'baseline statement removed'
    activities = ['InstallationPlanSlice', 'InstallationApplySlice', 'InstallationRecoverySlice',
                  'GhSdpClientSlice', 'ManualAdoptionTrial']
    for name in activities:
        assert f'{name} has implementation-status = planned.' in source
    assert 'SdpToolProcess contains InstallationExecutor.' in source
    assert 'GhSdpProcess contains GhSdpLauncher.' in source
    assert 'GhSdpProcess contains InstallationExecutor.' not in source
    negative = {}
    bad_models = {
        'unpermitted-message': source.replace('InstallationPlanningCallsProtocol permits PlanInstallationRequest.\n', ''),
        'invalid-reply': source.replace('via InstallationPlanningCalls reply-to 1.', 'via InstallationPlanningCalls reply-to 999.'),
    }
    with tempfile.TemporaryDirectory(prefix='ipd-negative-') as temp:
        for name, text in bad_models.items():
            assert text != source
            path = Path(temp) / (name + '.design')
            path.write_text(text)
            r = subprocess.run([str(tool), 'check', str(path)], cwd=ROOT, capture_output=True, text=True)
            data = json.loads(r.stdout)
            codes = sorted({d['code'] for d in data['diagnostics']})
            assert r.returncode != 0 and not data['valid']
            assert codes and 'NONCANONICAL_FORM' not in codes, codes
            negative[name] = codes
    return {'valid': True, 'symbolCounts': dict(sorted(Counter(d['kind'] for d in report['ast']['declarations']).items())),
            'baselineStatementsPreserved': BASELINE, 'newActivitiesRemainPlanned': activities,
            'negativeCases': negative}


def generate(tool, dest):
    dest.mkdir()
    evidence = checks(tool)
    revision = digest((ROOT / MODEL).read_bytes())
    index = ['# SDPTool installation — generated design review', '',
             'Generated by review.py through the SDL toolkit; do not hand-edit.', '',
             f'Model revision: `{revision}`.', '',
             'These are planned design facts, not an implemented Go installer.', '',
             '| View | Generated selection |', '| --- | --- |']
    selections = []
    for folder, title, vp, query in SELECTIONS:
        uri = f'sdl-view://sdp-vnow/{vp}?' + urlencode(query)
        run(tool, 'view', MODEL, '--uri', uri, '--output', dest / folder)
        manifest = json.loads((dest / folder / 'manifest.json').read_text())
        assert manifest['revision'] == revision and manifest['diagrams'], folder
        assert not [g for g in manifest.get('model_gaps', []) if g.get('code') in ('INCOMPLETE_PARTICIPATION', 'NO_PARTICIPANTS')]
        facts = {f['id'] for f in manifest['facts']}
        for diagram in manifest['diagrams']:
            assert diagram['source_facts'] and set(diagram['source_facts']) <= facts
        for rel, expected in manifest['outputs'].items():
            assert digest((dest / folder / rel).read_bytes()) == expected
        index.append(f'| {title} | [{vp}]({folder}/entry.md) |')
        selections.append({'path': folder + '/entry.md', 'uri': uri,
                           'diagrams': [d['id'] for d in manifest['diagrams']]})
    index += ['', '## Coverage and limits', '',
              'VP01: use cases; VP02: process/unit ownership; VP06: planned delivery; '
              'VP07: feature allocation; VP08: validated sequences; VP09: persistent/logical data.', '',
              'VP10 is intentionally absent: JSON documents have no fixed-bit packet encoding. '
              'Sequence ordering is modeled; mutation, signature and recovery semantics are not executed. '
              'Diagrams are Mermaid source; host rendering and native UI appearance are not verified here.', '',
              '[Authored contract](../Contract.md) · [Scenario review](../Scenarios.md) · '
              '[Design plan](../Plan.md) · [Evidence](../Evidence.md)', '']
    (dest / 'index.md').write_text('\n'.join(index))
    outputs = {str(p.relative_to(dest)): digest(p.read_bytes()) for p in sorted(dest.rglob('*')) if p.is_file()}
    source_files = subprocess.check_output(['git', 'ls-files', 'SDL/go'], cwd=ROOT, text=True).splitlines()
    # Never inspect unrelated untracked sourceinput drafts.
    source_digests = {p: digest((ROOT / p).read_bytes()) for p in source_files}
    provenance = {'schemaVersion': 'ipd-review/1', 'model': str(MODEL), 'revision': revision,
                  'generator': 'SDL Go CLI view', 'generatorBinarySha256': digest(tool.read_bytes()),
                  'generatorSourceDigest': digest(json.dumps(source_digests, sort_keys=True).encode()),
                  'orchestratorSha256': digest(Path(__file__).read_bytes()),
                  'selections': selections, 'checks': evidence, 'outputs': outputs}
    (dest / 'provenance.json').write_text(json.dumps(provenance, indent=2, sort_keys=True) + '\n')
    return provenance


def tree(path):
    return {str(p.relative_to(path)): p.read_bytes() for p in path.rglob('*') if p.is_file()}


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--sdl', required=True, type=Path)
    ap.add_argument('--output', type=Path, default=HERE / 'review')
    ap.add_argument('--check', action='store_true', help='compare fresh output to existing output without writing it')
    args = ap.parse_args()
    tool = args.sdl.resolve(strict=True)
    output = args.output.resolve()
    if not args.check and output.exists():
        ap.error('output already exists; use --check or a new destination')
    with tempfile.TemporaryDirectory(prefix='ipd-review-') as temp:
        a, b = Path(temp) / 'first', Path(temp) / 'second'
        proof = generate(tool, a)
        generate(tool, b)
        assert tree(a) == tree(b), 'nondeterministic generated review'
        if args.check:
            assert tree(output) == tree(a), 'stored review differs; inspect drift before regeneration'
        else:
            shutil.copytree(a, output)
    print(json.dumps({'status': 'passed', 'mode': 'check' if args.check else 'generate',
                      'modelRevision': proof['revision'], 'selectedViews': len(SELECTIONS),
                      'diagramCount': sum(len(s['diagrams']) for s in proof['selections']),
                      'files': len(proof['outputs']) + 1, 'checks': proof['checks']}, sort_keys=True))


if __name__ == '__main__':
    main()
