package sdptool

import (
	"bytes"
	"flag"
	"fmt"
	"github.com/Hans-Einar/SDP/SDPTool/presentation"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

var releaseHeading = regexp.MustCompile(`^## \[((?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z.-]+)?)\] - ([0-9]{4}-[0-9]{2}-[0-9]{2})$`)

// ReleaseLogs projects reviewed notes verbatim. It cannot attest publication.
// Git subjects are deliberately not treated as accepted release contents.
func ReleaseLogs(notes string) (map[string][]byte, error) {
	logs := map[string][]byte{}
	var version string
	var body []string
	var fence byte
	fenceLength := 0
	flush := func() error {
		if version == "" {
			return nil
		}
		text := strings.TrimSpace(strings.Join(body, "\n"))
		if !strings.Contains(text, "\n### ") {
			return fmt.Errorf("release %s has no change categories", version)
		}
		logs[version] = []byte("<!-- Generated by sdptool release-log from RELEASE-NOTES.md; do not edit. -->\n\n" + text + "\n")
		return nil
	}
	for _, line := range strings.Split(strings.ReplaceAll(notes, "\r\n", "\n"), "\n") {
		trim := strings.TrimLeft(line, " ")
		if len(line)-len(trim) <= 3 && len(trim) >= 3 && (trim[0] == '`' || trim[0] == '~') {
			n := 1
			for n < len(trim) && trim[n] == trim[0] {
				n++
			}
			if n >= 3 {
				if fenceLength == 0 && (trim[0] != '`' || !strings.ContainsRune(trim[n:], '`')) {
					fence, fenceLength = trim[0], n
				} else if trim[0] == fence && n >= fenceLength && strings.TrimSpace(trim[n:]) == "" {
					fenceLength = 0
				}
				body = append(body, line)
				continue
			}
		}
		if fenceLength == 0 && strings.HasPrefix(line, "## ") {
			if e := flush(); e != nil {
				return nil, e
			}
			version = ""
			body = nil
			if line == "## [Unreleased]" {
				continue
			}
			match := releaseHeading.FindStringSubmatch(line)
			if match == nil {
				return nil, fmt.Errorf("invalid release heading: %s", line)
			}
			if _, e := time.Parse("2006-01-02", match[2]); e != nil {
				return nil, e
			}
			version = match[1]
			if _, exists := logs[version]; exists {
				return nil, fmt.Errorf("duplicate release %s", version)
			}
		}
		if version != "" {
			body = append(body, line)
		}
	}
	if fenceLength != 0 {
		return nil, fmt.Errorf("unterminated code fence in release notes")
	}
	if e := flush(); e != nil {
		return nil, e
	}
	if len(logs) == 0 {
		return nil, fmt.Errorf("no versioned release notes found")
	}
	return logs, nil
}

func releaseLog(root string, args []string, out, errs io.Writer, jsonMode bool) int {
	fs := flag.NewFlagSet("release-log", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	version := fs.String("version", "", "release section, e.g. 1.1.0")
	notes := fs.String("notes", "RELEASE-NOTES.md", "canonical notes, relative to selected root")
	output := fs.String("output", "", "output file (or directory with --all)")
	all := fs.Bool("all", false, "all versioned sections")
	check := fs.Bool("check", false, "compare existing output without writes")
	fail := func(e error) int { return reportMode(errs, failure("release-log", e), jsonMode) }
	if e := fs.Parse(args); e != nil {
		return fail(e)
	}
	if fs.NArg() != 0 || (*all == (*version != "")) || (*all && *output == "") || (*check && *output == "") {
		return fail(fmt.Errorf("select --version VERSION or --all; --all/--check require --output"))
	}
	path := *notes
	if !filepath.IsAbs(path) {
		path = filepath.Join(root, path)
	}
	b, e := readSource(path)
	if e != nil {
		return fail(e)
	}
	logs, e := ReleaseLogs(string(b))
	if e != nil {
		return fail(e)
	}
	if !*all {
		b, ok := logs[*version]
		if !ok {
			return fail(fmt.Errorf("release %q missing from canonical notes", *version))
		}
		logs = map[string][]byte{*version: b}
		if *output == "" {
			e = presentation.Default().Write(out, map[string]any{"schema": Version, "operation": "release-log", "markdown": string(b)}, jsonMode)
			if e != nil {
				return fail(e)
			}
			return 0
		}
	}
	// Check every existing destination first. Never overwrite an immutable log.
	paths := map[string][]byte{}
	for v, b := range logs {
		p := *output
		if *all {
			p = filepath.Join(p, v+".md")
		}
		if !filepath.IsAbs(p) {
			p = filepath.Join(root, p)
		}
		old, err := os.ReadFile(p)
		if err == nil {
			if !bytes.Equal(old, b) {
				return fail(fmt.Errorf("release log differs: %s", p))
			}
		} else if *check || !os.IsNotExist(err) {
			return fail(err)
		}
		paths[p] = b
	}
	for p, b := range paths {
		if *check {
			continue
		}
		if e = os.MkdirAll(filepath.Dir(p), 0755); e != nil {
			return fail(e)
		}
		f, err := os.OpenFile(p, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0644)
		if os.IsExist(err) {
			old, readErr := os.ReadFile(p)
			if readErr == nil && bytes.Equal(old, b) {
				continue
			}
		}
		if err != nil {
			return fail(err)
		}
		_, err = f.Write(b)
		closeErr := f.Close()
		if err != nil {
			return fail(err)
		}
		if closeErr != nil {
			return fail(closeErr)
		}
	}
	if e := presentation.Default().Write(out, map[string]any{"schema": Version, "operation": "release-log", "count": len(paths), "status": map[bool]string{true: "verified", false: "generated"}[*check]}, jsonMode); e != nil {
		return fail(e)
	}
	return 0
}
