package sdptool

import (
	"bytes"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

var releaseHeading = regexp.MustCompile(`^## \[((?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z.-]+)?)\] - ([0-9]{4}-[0-9]{2}-[0-9]{2})$`)

// ReleaseLogs projects reviewed notes verbatim. It cannot attest publication.
// Git subjects are deliberately not treated as accepted release contents.
func ReleaseLogs(notes string) (map[string][]byte, error) {
	logs := map[string][]byte{}
	var version string
	var body []string
	fence := ""
	flush := func() error {
		if version == "" {
			return nil
		}
		text := strings.TrimSpace(strings.Join(body, "\n"))
		if !strings.Contains(text, "\n### ") {
			return fmt.Errorf("release %s has no change categories", version)
		}
		logs[version] = []byte("<!-- Generated by sdptool release-log from RELEASE-NOTES.md; do not edit. -->\n\n" + text + "\n")
		return nil
	}
	for _, line := range strings.Split(strings.ReplaceAll(notes, "\r\n", "\n"), "\n") {
		trim := strings.TrimSpace(line)
		if strings.HasPrefix(trim, "```") || strings.HasPrefix(trim, "~~~") {
			marker := trim[:3]
			if fence == "" {
				fence = marker
			} else if fence == marker {
				fence = ""
			}
			body = append(body, line)
			continue
		}
		if fence == "" && strings.HasPrefix(line, "## ") {
			if e := flush(); e != nil {
				return nil, e
			}
			version = ""
			body = nil
			if line == "## [Unreleased]" {
				continue
			}
			match := releaseHeading.FindStringSubmatch(line)
			if match == nil {
				return nil, fmt.Errorf("invalid release heading: %s", line)
			}
			if _, e := time.Parse("2006-01-02", match[2]); e != nil {
				return nil, e
			}
			version = match[1]
			if _, exists := logs[version]; exists {
				return nil, fmt.Errorf("duplicate release %s", version)
			}
		}
		if version != "" {
			body = append(body, line)
		}
	}
	if e := flush(); e != nil {
		return nil, e
	}
	if len(logs) == 0 {
		return nil, fmt.Errorf("no versioned release notes found")
	}
	return logs, nil
}

func releaseLog(root string, args []string, out, errs io.Writer) int {
	fs := flag.NewFlagSet("release-log", flag.ContinueOnError)
	fs.SetOutput(errs)
	version := fs.String("version", "", "release section, e.g. 1.1.0")
	notes := fs.String("notes", "RELEASE-NOTES.md", "canonical notes, relative to selected root")
	output := fs.String("output", "", "output file (or directory with --all)")
	all := fs.Bool("all", false, "all versioned sections")
	check := fs.Bool("check", false, "compare existing output without writes")
	fail := func(e error) int { return report(errs, failure("release-log", e)) }
	if e := fs.Parse(args); e != nil {
		return fail(e)
	}
	if fs.NArg() != 0 || (*all == (*version != "")) || (*all && *output == "") || (*check && *output == "") {
		return fail(fmt.Errorf("select --version VERSION or --all; --all/--check require --output"))
	}
	path := *notes
	if !filepath.IsAbs(path) {
		path = filepath.Join(root, path)
	}
	b, e := readSource(path)
	if e != nil {
		return fail(e)
	}
	logs, e := ReleaseLogs(string(b))
	if e != nil {
		return fail(e)
	}
	if !*all {
		b, ok := logs[*version]
		if !ok {
			return fail(fmt.Errorf("release %q missing from canonical notes", *version))
		}
		logs = map[string][]byte{*version: b}
		if *output == "" {
			_, e = out.Write(b)
			if e != nil {
				return fail(e)
			}
			return 0
		}
	}
	// Check every existing destination first. Never overwrite an immutable log.
	paths := map[string][]byte{}
	for v, b := range logs {
		p := *output
		if *all {
			p = filepath.Join(p, v+".md")
		}
		if !filepath.IsAbs(p) {
			p = filepath.Join(root, p)
		}
		old, err := os.ReadFile(p)
		if err == nil {
			if !bytes.Equal(old, b) {
				return fail(fmt.Errorf("release log differs: %s", p))
			}
		} else if *check || !os.IsNotExist(err) {
			return fail(err)
		}
		paths[p] = b
	}
	for p, b := range paths {
		if *check {
			continue
		}
		if e = os.MkdirAll(filepath.Dir(p), 0755); e != nil {
			return fail(e)
		}
		f, err := os.OpenFile(p, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0644)
		if os.IsExist(err) {
			old, readErr := os.ReadFile(p)
			if readErr == nil && bytes.Equal(old, b) {
				continue
			}
		}
		if err != nil {
			return fail(err)
		}
		_, err = f.Write(b)
		closeErr := f.Close()
		if err != nil {
			return fail(err)
		}
		if closeErr != nil {
			return fail(closeErr)
		}
	}
	fmt.Fprintf(out, "%d release log(s) %s\n", len(paths), map[bool]string{true: "verified", false: "generated"}[*check])
	return 0
}
