treemap-beta
  "Aptering - statisk prøve"
    "Måling"
      "Lengde 412,0 cm": 7.5
      "Diameter 28,4 cm": 7.5
    "Aptering"
      "Treslag / Sortiment<br/>Gran<br/>Sagtømmer": 11.25
      "Apteringsforslag<br/>Sagtømmer 430 cm - topp 26 cm<br/>Massevirke 310 cm - topp 18 cm<br/>Canonical - Alternativ 1": 22.5
      "Stammen i aggregatet<br/>Ingen låste feil<br/>Nåposisjon 412,0 cm": 11.25
    "Stammeforløp"
      "Predikert - Målt - Plan - Rest<br/>[Stammeprofil er plassholder]<br/>taperNOR - Mixed<br/>Følger aggregat - 412,0 cm": 40
