#!/usr/bin/env python3
"""BP1 research probe: invoke the existing Go SDL tool, never parse SDL here.

Run with --output outside the repository. Generated evidence is a study record,
not a production blueprint generator or a design-to-code conformance checker.
"""
import argparse
import hashlib
import json
import subprocess
import tempfile
from pathlib import Path

BASE = '2ff71c4a033aa1393e02657777e85f5fb67ccefd'
MODEL = 'SDP/03--Architecture/SDPTool.design'
ROOT = Path(__file__).resolve().parents[4]


def run(args, cwd=ROOT):
    result = subprocess.run(args, cwd=cwd, text=True, capture_output=True)
    if result.returncode:
        raise RuntimeError(f'{args}: {result.stderr or result.stdout}')
    return result.stdout


def digest(data):
    return hashlib.sha256(data.encode()).hexdigest()


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--go', default='go')
    ap.add_argument('--output', type=Path, required=True)
    args = ap.parse_args()
    output = args.output.resolve()
    if output == ROOT or ROOT in output.parents:
        ap.error('use an output directory outside the repository')
    output.mkdir(parents=True, exist_ok=False)
    # Pin executable source too. No untracked sourceinput draft is read or used.
    run(['git', 'diff', '--exit-code', BASE, '--', 'SDL/go/parser',
         'SDL/go/viewpoint', 'SDL/go/documents', 'SDL/go/cmd/sdl', 'SDL/go/go.mod', 'SDL/go/go.sum'])
    current = run(['git', 'show', BASE + ':' + MODEL])
    additions = '''PreviewCoordinator owns ValidateSnapshotRevision.
ValidateSnapshotRevision allocated-to SdpToolProcess in mode StandalonePreview.
ValidateSnapshotRevision contributes-to SdpTool.
ValidateSnapshotRevision realizes DesignPreview.
UnsavedSourcePreview addresses ValidateSnapshotRevision.
'''
    target = current.replace('language design-core version 0.5.\n',
                             'language design-core version 0.5.\nfunctionality ValidateSnapshotRevision.\n', 1) + additions
    assert target.count('ViewerBridge owns DeliverViewBundle.') == 1
    drift = target.replace('ViewerBridge owns DeliverViewBundle.',
                           'PreviewCoordinator owns DeliverViewBundle.')
    report = {'baseline': BASE, 'model': MODEL,
              'go': run([args.go, 'version']).strip(),
              'probe_sha256': hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
              'scope': 'Existing Go parser/projection experiment; authored target and guard; no worker trial',
              'cases': {}}
    markdown = ['# BP1 model extracts — generated research evidence\n',
                'Generated by probe.py through the existing Go SDL parser and viewpoint tool.\n',
                'Target and drift inputs are study proposals, not adopted system design.\n']
    with tempfile.TemporaryDirectory(prefix='sdp-bp1-') as tmp:
        tmp = Path(tmp)
        tool = tmp / 'sdl'
        run([args.go, 'build', '-o', str(tool), './cmd/sdl'], ROOT / 'SDL/go')
        for label, source in [('current', current), ('target', target), ('ownership-drift', drift)]:
            # Canonicalization also invokes current semantic validation.
            raw = tmp / (label + '.raw')
            raw.write_text(source)
            canonical = run([str(tool), 'format', str(raw)])
            path = output / (label + '.design')
            path.write_text(canonical)
            checked = json.loads(run([str(tool), 'check', str(path)]))
            views = {}
            for vp, focus, depth in [('VP03', 'PreviewCoordinator', 1),
                                      ('VP03', 'SdpToolProcess', 2),
                                      ('VP06', 'UnsavedSourcePreview', 2)]:
                key = f'{vp}-{focus}'
                bundle = tmp / f'{label}-{key}'
                uri = f'sdl-view://bp1/{vp}?focus={focus}&direction=both&depth={depth}'
                if vp == 'VP03':
                    uri += '&diagram=VP03-DesignPreview'
                run([str(tool), 'view', str(path), '--uri', uri, '--output', str(bundle)])
                manifest = json.loads((bundle / 'manifest.json').read_text())
                views[key] = {'uri': uri, 'revision': manifest['revision'],
                              'fact_count': len(manifest['facts']),
                              'manifest_sha256': hashlib.sha256((bundle / 'manifest.json').read_bytes()).hexdigest(),
                              'ownership_facts': [f for f in manifest['facts']
                                  if f.get('verb') == 'owns' and f.get('object') in
                                  ('AcceptSourceSnapshot', 'BuildDesignPreview', 'ValidateSnapshotRevision', 'DeliverViewBundle')],
                              'diagram_ids': [d['id'] for d in manifest['diagrams']]}
                if vp == 'VP03':
                    markdown += [f'\n# {label}: {focus}\n', (bundle / 'entry.md').read_text()]
            owner_facts = [f['text'] for f in views['VP03-SdpToolProcess']['ownership_facts']
                           if f.get('verb') == 'owns' and f.get('object') == 'DeliverViewBundle']
            # Deliberately authored scope assertion, not a general SDL rule.
            guard = owner_facts == ['ViewerBridge owns DeliverViewBundle.']
            report['cases'][label] = {'valid': checked['valid'],
                'source_sha256': digest(canonical), 'views': views,
                'preserves_authored_delivery_owner': guard}
        assert all(c['valid'] for c in report['cases'].values())
        assert report['cases']['current']['preserves_authored_delivery_owner']
        assert report['cases']['target']['preserves_authored_delivery_owner']
        assert not report['cases']['ownership-drift']['preserves_authored_delivery_owner']
    (output / 'Evidence.json').write_text(json.dumps(report, indent=2, sort_keys=True) + '\n')
    (output / 'Model-extracts.md').write_text('\n'.join(markdown))
    print(json.dumps({'output': str(output), 'cases_valid': 3,
                      'authored_guard_rejects_drift': True}))


if __name__ == '__main__':
    main()
