flowchart LR
    n_InstallProjectProcess["InstallProjectProcess (usecase)"]
    n_ProjectMaintainer["ProjectMaintainer (actor)"]
    n_SdpTool["SdpTool (feature)"]
    n_ProjectMaintainer -->|pursues| n_InstallProjectProcess
    n_SdpTool -->|supports| n_InstallProjectProcess
