package codegen

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestGeneratedCollectionConstructors(t *testing.T) {
	const source = `sdui 0.3;
ref: nav "never-opened.sdl";
leaf=<nodes=tree("Navigation",callback=nav.Activate.@invoke),rows=list("Entries")>;
alias=leaf;
page=[left=alias,right=alias];`
	generated, err := Generate(source, "page", "generated")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.HasPrefix(generated, []byte("// Code generated by sdui-go-model/2;")) {
		t.Fatal("incorrect generator identity")
	}
	module, err := filepath.Abs("..")
	if err != nil {
		t.Fatal(err)
	}
	dir := t.TempDir()
	harness := fmt.Sprintf(`package generated
import (
 "reflect"
 "testing"
 ui "github.com/Hans-Einar/SDP/SDUI/go/parser"
)
func TestRoundTrip(t *testing.T) {
 doc, roots, err := ui.Compile(%q)
 if err != nil { t.Fatal(err) }
 if UIProfile != "sdui/0.3" || UIASTFormat != "sdui-ast/0.3" { t.Fatal("metadata") }
 root := Root()
 if !reflect.DeepEqual(doc,Document()) || !reflect.DeepEqual(roots["page"],root) { t.Fatal("generated source/provenance differs") }
 normalized,err:=ui.Normalize(Document())
 if err!=nil || !reflect.DeepEqual(normalized["page"],root) {t.Fatal("document/root mismatch",err)}
 root.Walk(func(n *ui.Instance) {if n.Profile!=UIProfile {t.Fatal("lost profile",n.Path)}})
 left,right:=root.Rows[0][0],root.Rows[0][1]
 if len(left.Uses)!=2 || left.Uses[1].Span==right.Uses[1].Span || left.Path==right.Path {t.Fatal("lost reuse identity")}
 if left.Rows[0][0].Arguments["callback"].(ui.Reference).Object!="Activate" {t.Fatal("lost callback")}
 left.Rows[0][0].Profile=""
 left.Uses[0].Definition="mutated"
 if _,err:=ui.EffectiveProfile(root);err==nil {t.Fatal("mixed profile accepted")}
 if right.Rows[0][0].Profile!=UIProfile || !reflect.DeepEqual(roots["page"],Root()) {t.Fatal("shared constructor state")}
}
`, source)
	files := map[string][]byte{
		"model_gen.go":      generated,
		"roundtrip_test.go": []byte(harness),
		"go.mod":            []byte(fmt.Sprintf("module generated-collections-test\n\ngo 1.26.0\nrequire github.com/Hans-Einar/SDP/SDUI/go v0.0.0\nreplace github.com/Hans-Einar/SDP/SDUI/go => %q\n", module)),
	}
	for name, data := range files {
		if err := os.WriteFile(filepath.Join(dir, name), data, 0600); err != nil {
			t.Fatal(err)
		}
	}
	cmd := exec.Command(filepath.Join(runtime.GOROOT(), "bin", "go"), "test", "-count=1", "./...")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOWORK=off")
	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("generated collection round trip: %v\n%s", err, output)
	}
}

func TestLegacyGeneratedBytesUnchanged(t *testing.T) {
	// This file is the repaired, committed 0.2 prerequisite; do not regenerate it
	// here. Exact bytes catch added empty Profile literals or version metadata.
	source, err := os.ReadFile("../../../SDL/go/examples/edit-apt-cell.sdui")
	if err != nil {
		t.Fatal(err)
	}
	expected, err := os.ReadFile("../../../SDL/go/examples/generatedmodel/ui_gen.go")
	if err != nil {
		t.Fatal(err)
	}
	actual, err := Generate(string(source), "page", "generatedmodel")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(actual, expected) {
		t.Fatal("0.2 generated bytes changed")
	}
	if strings.Contains(string(actual), "Profile: string(\"\")") || strings.Contains(string(actual), "UIASTFormat") {
		t.Fatal("legacy metadata changed")
	}
}
