package codegen

import (
	"crypto/sha256"
	"fmt"
	"github.com/Hans-Einar/SDP/SDUI/go/parser"
	"go/format"
)

const Version = "sdui-go-model/1"
const ParserPackage = "github.com/Hans-Einar/SDP/SDUI/go/parser"

func Generate(source, entry, pkg string) ([]byte, error) {
	if !ValidPackage(pkg) {
		return nil, fmt.Errorf("invalid package name")
	}
	doc, roots, e := parser.Compile(source)
	if e != nil {
		return nil, e
	}
	root := roots[entry]
	if root == nil {
		return nil, fmt.Errorf("unknown SDUI entry %q", entry)
	}
	aliases := map[string]string{ParserPackage: "ui"}
	d, e := Literal(doc, aliases)
	if e != nil {
		return nil, e
	}
	r, e := Literal(root, aliases)
	if e != nil {
		return nil, e
	}
	return format.Source([]byte(fmt.Sprintf("// Code generated by %s; DO NOT EDIT.\npackage %s\nimport ui %q\nconst UISourceSHA256 = %q\nfunc Document() *ui.Document { return %s }\nfunc Root() *ui.Instance { return %s }\n", Version, pkg, ParserPackage, fmt.Sprintf("%x", sha256.Sum256([]byte(source))), d, r)))
}
