package codegen

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestGeneratedExtendedInputConstructors(t *testing.T) {
	const source = `sdui 0.3; ref: app "not-read.sdl";
Field=input("Label",value="å🙂\nnext",multiline=true,placeholder="",readOnly=false,callback=app.Save.@invoke);
Main=[left=Field;right=Field;basic=input("Basic");explicit=input("False",required=false)];
app.Save.setHandle(Main.left);`
	generated, err := Generate(source, "Main", "textmodel")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(generated), "// Code generated by sdui-go-model/2;") {
		t.Fatal("identity changed")
	}
	module, err := filepath.Abs("..")
	if err != nil {
		t.Fatal(err)
	}
	harness := fmt.Sprintf(`package textmodel
import("reflect";"testing";ui "github.com/Hans-Einar/SDP/SDUI/go/parser")
func TestRoundTrip(t *testing.T){
 doc, roots, err:=ui.Compile(%q);if err!=nil{t.Fatal(err)}
 root:=Root();if UIProfile!="sdui/0.3"||UIASTFormat!="sdui-ast/0.3"||!reflect.DeepEqual(doc,Document())||!reflect.DeepEqual(root,roots["Main"]){t.Fatal("metadata/source/span/reuse mismatch")}
 normalized,err:=ui.Normalize(Document());if err!=nil||!reflect.DeepEqual(root,normalized["Main"]){t.Fatal("normalization",err)}
 if _,err:=ui.ResolveInteractions(root);err!=nil{t.Fatal(err)}
 left,right:=root.Rows[0][0],root.Rows[1][0]
 p,err:=ui.InputOptions(left);if err!=nil||!p.Extended||!p.Multiline||!p.PlaceholderSet||p.Placeholder!=""||p.ReadOnly{t.Fatal(p,err)}
 basic,err:=ui.InputOptions(root.Rows[2][0]);if err!=nil||basic.Extended||len(root.Rows[2][0].Arguments)!=1{t.Fatal("omission lost",err)}
 explicit,err:=ui.InputOptions(root.Rows[3][0]);if err!=nil||!explicit.Extended||explicit.Required{t.Fatal("false presence lost",err)}
 if left.Argument("value")!="å🙂\nnext"||left.Uses[0].Span==right.Uses[0].Span||left.Path==right.Path{t.Fatal("Unicode/provenance lost")}
 left.Arguments["placeholder"]=ui.Literal{Kind:"string",Value:"changed"};left.Uses[0].Definition="changed"
 if right.Argument("placeholder")!=""||!reflect.DeepEqual(Root(),roots["Main"]){t.Fatal("constructors alias")}
}
`, source)
	dir := t.TempDir()
	for name, data := range map[string][]byte{"model.go": generated, "model_test.go": []byte(harness), "go.mod": []byte(fmt.Sprintf("module generated-text-test\n\ngo 1.26.0\nrequire github.com/Hans-Einar/SDP/SDUI/go v0.0.0\nreplace github.com/Hans-Einar/SDP/SDUI/go => %q\n", module))} {
		if err := os.WriteFile(filepath.Join(dir, name), data, 0600); err != nil {
			t.Fatal(err)
		}
	}
	cmd := exec.Command(filepath.Join(runtime.GOROOT(), "bin", "go"), "test", "-count=1", "./...")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOWORK=off")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("generated text constructors: %v\n%s", err, out)
	}
}
