package codegen

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestGeneratedInteractionIdentityRoundTrip(t *testing.T) {
	const source = `sdui 0.3;
ref: app "not-opened.sdl";
Part=[local=command("Local",toggle=true,checked=true,exclusive="g");button(command="local");button(command="/shared")];
Alias=Part;
Main=[shared=command("Shared",callback=app.Do.@invoke);left=Alias;right=Part;
menu("Actions")[item(command="shared");menuGroup("Options")[separator();menu("More",mode="submenu")[item(command="shared")]]];
d=dialog("Edit",callback=app.Save.@invoke)[field=input("Text",value="λ");button("Save",effect="accept")];
basic=button("Old",icon="old",tooltip="Legacy")];`
	generated, err := Generate(source, "Main", "commands")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(generated), "// Code generated by sdui-go-model/2;") {
		t.Fatal("new family version")
	}
	if _, err := Generate(source, "Part", "commands"); err == nil {
		t.Fatal("unresolved template generated as executable root")
	}
	module, err := filepath.Abs("..")
	if err != nil {
		t.Fatal(err)
	}
	harness := fmt.Sprintf(`package commands
import("reflect";"testing";ui "github.com/Hans-Einar/SDP/SDUI/go/parser")
func TestIdentity(t *testing.T){
 doc,roots,err:=ui.Compile(%q);if err!=nil{t.Fatal(err)}
 original:=roots["Main"];generated:=Root()
 if UIProfile!="sdui/0.3"||UIASTFormat!="sdui-ast/0.3"||!reflect.DeepEqual(doc,Document())||!reflect.DeepEqual(original,generated){t.Fatal("metadata/model/provenance mismatch")}
 want,err:=ui.ResolveInteractions(original);if err!=nil{t.Fatal(err)}
 got,err:=ui.ResolveInteractions(generated);if err!=nil||!reflect.DeepEqual(want,got){t.Fatal("resolved identity mismatch",err)}
 if got["Main/left/$r2c0"].Command!="Main/shared"||got["Main/right/local"].Scope!="Main/right"{t.Fatal(got)}
 restored,err:=ui.Normalize(Document());if err!=nil||!reflect.DeepEqual(restored["Main"],generated){t.Fatal("source normalize mismatch",err)}
 field,err:=ui.ResolveDialogField(generated,"Main/d","field");if err!=nil||field.Path!="Main/d/field"{t.Fatal(field,err)}
 field.Arguments["value"]=ui.Literal{Kind:"string",Value:"changed"}
 generated.Rows[1][0].Uses[0].Definition="changed"
 if !reflect.DeepEqual(original,Root()){t.Fatal("constructors alias")}
}
`, source)
	dir := t.TempDir()
	for name, data := range map[string][]byte{"model.go": generated, "model_test.go": []byte(harness), "go.mod": []byte(fmt.Sprintf("module interaction-test\n\ngo 1.26.0\nrequire github.com/Hans-Einar/SDP/SDUI/go v0.0.0\nreplace github.com/Hans-Einar/SDP/SDUI/go => %q\n", module))} {
		if err := os.WriteFile(filepath.Join(dir, name), data, 0600); err != nil {
			t.Fatal(err)
		}
	}
	cmd := exec.Command(filepath.Join(runtime.GOROOT(), "bin", "go"), "test", "-count=1", "./...")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOWORK=off")
	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("generated identity: %v\n%s", err, output)
	}
}
