package codegen

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestGeneratedPaneConstructors(t *testing.T) {
	const source = `sdui 0.3;
ref: app "not-opened.sdl";
leaf=page("Résumé")[header=input("Draft",value="λ")];
shared=tabs("Workspace",selected="second")[first=leaf;second=page("Résumé")[]];
Main=[pair=split(axis="horizontal",minFirst=0.1)[left=shared;right=shared];
live=tabs("Live",callback=app.Page.@invoke)[overview=page("Overview")[]];preview=input("Preview")];
app.Page.setHandle(Main.preview);`
	generated, err := Generate(source, "Main", "panes")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(generated), "// Code generated by sdui-go-model/2;") {
		t.Fatal("M1 invented another generator version")
	}
	module, err := filepath.Abs("..")
	if err != nil {
		t.Fatal(err)
	}
	harness := fmt.Sprintf(`package panes
import (
 "reflect"
 "testing"
 ui "github.com/Hans-Einar/SDP/SDUI/go/parser"
)
func TestRoundTrip(t *testing.T) {
 doc, roots, err := ui.Compile(%q)
 if err != nil {t.Fatal(err)}
 if UIProfile!="sdui/0.3" || UIASTFormat!="sdui-ast/0.3" {t.Fatal("metadata")}
 if !reflect.DeepEqual(doc,Document()) || !reflect.DeepEqual(roots["Main"],Root()) {t.Fatal("model/provenance mismatch")}
 normalized,err:=ui.Normalize(Document());if err!=nil || !reflect.DeepEqual(normalized["Main"],Root()) {t.Fatal("normalization mismatch",err)}
 root:=Root(); split:=root.Rows[0][0]; sides,err:=ui.PaneChildren(split)
 if err!=nil || sides[0].ID!="left" || sides[1].ID!="right" {t.Fatal("split identity",err)}
 pages,err:=ui.PaneChildren(sides[0].Node)
 if err!=nil || pages[0].Node.Path==sides[1].Node.Rows[0][0].Path || len(pages[0].Node.Uses)!=1 {t.Fatal("page reuse identity",err)}
 if split.Arguments["proportion"].(ui.Literal).Value!=float64(.5) {t.Fatal("normalized default missing")}
 if root.Rows[1][0].Arguments["callback"].(ui.Reference).Object!="Page" || len(Document().Connections)!=1 {t.Fatal("binding lost")}
 split.Arguments["proportion"]=ui.Literal{Kind:"number",Value:float64(.75)}
 pages[0].Node.Rows[0][0].Arguments["value"]=ui.Literal{Kind:"string",Value:"changed"}
 if !reflect.DeepEqual(roots["Main"],Root()) {t.Fatal("constructors share mutable state")}
}
`, source)
	dir := t.TempDir()
	for name, data := range map[string][]byte{
		"panes_gen.go":  generated,
		"panes_test.go": []byte(harness),
		"go.mod":        []byte(fmt.Sprintf("module generated-panes-test\n\ngo 1.26.0\nrequire github.com/Hans-Einar/SDP/SDUI/go v0.0.0\nreplace github.com/Hans-Einar/SDP/SDUI/go => %q\n", module)),
	} {
		if err := os.WriteFile(filepath.Join(dir, name), data, 0600); err != nil {
			t.Fatal(err)
		}
	}
	cmd := exec.Command(filepath.Join(runtime.GOROOT(), "bin", "go"), "test", "-count=1", "./...")
	cmd.Dir, cmd.Env = dir, append(os.Environ(), "GOWORK=off")
	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("generated pane round trip: %v\n%s", err, output)
	}
}
