package codegen

import (
	"crypto/sha256"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"testing"
)

func TestLegacyPreviewConstructorBytes(t *testing.T) {
	// Independent baseline: Generate from the delivered 90a94b5 git archive.
	for profile, want := range map[string]string{
		"0.2": "123b27954f50489bb90819feb58616c01f14b749d749a48d17a154cfde612817",
		"0.3": "543861069478a3305f5dcf03f3a2e870522d44efa1f2c5ed16ea1264857ef368",
	} {
		source := `sdui ` + profile + `; ref: art "unopened"; Main=[picture=svg(art.Image.@draw,label="Legacy");text="# Old prose"];`
		out, err := Generate(source, "Main", "legacy")
		if err != nil {
			t.Fatal(err)
		}
		if got := fmt.Sprintf("%x", sha256.Sum256(out)); got != want {
			t.Fatal(profile, "legacy generated bytes changed", got)
		}
	}
}

// Compile and execute the emitted package: comparing source text alone would not
// catch lost normalized text, aliases, provenance, or invalid selected-root refs.
func TestGeneratedAllFamilyPreviewConstructors(t *testing.T) {
	source, err := os.ReadFile("../parser/testdata/wci4-all-families.sdui")
	if err != nil {
		t.Fatal(err)
	}
	generated, err := Generate(string(source), "Main", "allfamilies")
	if err != nil {
		t.Fatal(err)
	}
	module, err := filepath.Abs("..")
	if err != nil {
		t.Fatal(err)
	}
	harness := fmt.Sprintf(`package allfamilies
import("reflect";"testing";ui "github.com/Hans-Einar/SDP/SDUI/go/parser")
func TestRoundTrip(t *testing.T){
 doc,roots,err:=ui.Compile(%q);if err!=nil{t.Fatal(err)}
 root:=Root();if UIProfile!="sdui/0.3"||UIASTFormat!="sdui-ast/0.3"||!reflect.DeepEqual(Document(),doc)||!reflect.DeepEqual(root,roots["Main"]){t.Fatal("constructor metadata/source/span mismatch")}
 normalized,err:=ui.Normalize(Document());if err!=nil||!reflect.DeepEqual(root,normalized["Main"]){t.Fatal("Normalize(Document) differs",err)}
 if _,err:=ui.ResolveInteractions(root);err!=nil{t.Fatal(err)}
 seen:=map[string]*ui.Instance{};root.Walk(func(n *ui.Instance){seen[n.Path]=n})
 a,b:=seen["Main/reading"],seen["Main/hiddenReading"]
 for _,n:=range []*ui.Instance{a,b,seen["Main/image"]}{p,err:=ui.PreviewOptions(n);if err!=nil||!p.Explicit{t.Fatal(n,p,err)}}
 if a.Text!="# Reading\nPlain prose"||a.Kind!="markdown"||a.Widget!=""||len(a.Arguments)!=3||a.Uses[0].Span==b.Uses[0].Span{t.Fatal("normalization/provenance")}
 if doc.Definitions[0].Root.Kind!="widget"||doc.Definitions[0].Root.Text!=nil{t.Fatal("source AST shape changed")}
 a.Arguments["description"]=ui.Literal{Kind:"string",Value:"changed"};a.Uses[0].Definition="changed"
 if b.Argument("description")!="Reading document"||!reflect.DeepEqual(Root(),roots["Main"]){t.Fatal("constructors alias")}
}
`, string(source))
	dir := t.TempDir()
	for name, data := range map[string][]byte{"model.go": generated, "model_test.go": []byte(harness), "go.mod": []byte(fmt.Sprintf("module generated-allfamilies-test\n\ngo 1.26.0\nrequire github.com/Hans-Einar/SDP/SDUI/go v0.0.0\nreplace github.com/Hans-Einar/SDP/SDUI/go => %q\n", module))} {
		if err := os.WriteFile(filepath.Join(dir, name), data, 0600); err != nil {
			t.Fatal(err)
		}
	}
	cmd := exec.Command(filepath.Join(runtime.GOROOT(), "bin", "go"), "test", "-count=1", "./...")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOWORK=off")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("generated all-family constructors: %v\n%s", err, out)
	}
}
