package codegen

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestGeneratedScalarConstructorsPreserveNumericProvenance(t *testing.T) {
	const source = `sdui 0.3;
ref: app "not-read.sdl";
Field=number("Amount",min=-0,max=1e1,step=1.00e-1,value=0.30,callback=app.Save.@invoke);
Main=[left=Field;right=Field;flag=checkbox("Flag",value=true);choice=select("Choice",value="compact");slide=slider("Slide",min=-9007199254740991,max=9007199254740991,step=1,value=0)];
app.Save.setHandle(Main.left);`
	output, err := Generate(source, "Main", "scalars")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(output), "// Code generated by sdui-go-model/2;") {
		t.Fatal("family generator version drift")
	}
	module, err := filepath.Abs("..")
	if err != nil {
		t.Fatal(err)
	}
	harness := fmt.Sprintf(`package scalars
import("reflect";"testing";ui "github.com/Hans-Einar/SDP/SDUI/go/parser")
func TestConstructors(t *testing.T){
 doc,roots,err:=ui.Compile(%q);if err!=nil{t.Fatal(err)}
 root:=Root();if UIProfile!="sdui/0.3"||UIASTFormat!="sdui-ast/0.3"||!reflect.DeepEqual(doc,Document())||!reflect.DeepEqual(root,roots["Main"]){t.Fatal("metadata/provenance mismatch")}
 normalized,err:=ui.Normalize(Document());if err!=nil||!reflect.DeepEqual(root,normalized["Main"]){t.Fatal("generated source normalization",err)}
 min,max,step,value,err:=ui.NumericArguments(root.Rows[0][0]);if err!=nil||min!="-0"||max!="1e1"||step!="1.00e-1"||value!="0.30"{t.Fatal(min,max,step,value,err)}
 if _,err:=ui.ResolveInteractions(root);err!=nil{t.Fatal(err)}
 if root.Rows[0][0].Uses[0].Span==root.Rows[1][0].Uses[0].Span{t.Fatal("reused instances collapsed")}
 root.Rows[0][0].Arguments["value"]=ui.Literal{Kind:"number-lexeme",Value:"0.4"};root.Rows[0][0].Uses[0].Definition="changed"
 if root.Rows[1][0].Arguments["value"].(ui.Literal).Value!="0.30"||!reflect.DeepEqual(Root(),roots["Main"]){t.Fatal("mutable constructors alias")}
}
`, source)
	dir := t.TempDir()
	for name, data := range map[string][]byte{"model.go": output, "model_test.go": []byte(harness), "go.mod": []byte(fmt.Sprintf("module scalar-generated-test\n\ngo 1.26.0\nrequire github.com/Hans-Einar/SDP/SDUI/go v0.0.0\nreplace github.com/Hans-Einar/SDP/SDUI/go => %q\n", module))} {
		if err := os.WriteFile(filepath.Join(dir, name), data, 0600); err != nil {
			t.Fatal(err)
		}
	}
	command := exec.Command(filepath.Join(runtime.GOROOT(), "bin", "go"), "test", "-count=1", "./...")
	command.Dir = dir
	command.Env = append(os.Environ(), "GOWORK=off")
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("generated scalar model: %v\n%s", err, output)
	}
}
